/*
 * Godine Order Restful API
 * Godine Order Restful API document.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: blackhorseya@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * Generator version: 7.7.0-SNAPSHOT
 */

import http from 'k6/http';
import {check, group, sleep} from 'k6';

export const options = {
  cloud: {
    // Project: Default project
    projectID: 3690299,
    // Test runs with the same name groups test runs together.
    name: 'godine order restful api test',
  },

  // define thresholds
  thresholds: {
    http_req_failed: ['rate<0.01'], // http errors should be less than 1%
    http_req_duration: ['p(99)<1000'], // 99% of requests should be below 1s
  },

  // define scenarios
  scenarios: {
    // arbitrary name of scenario
    average_load: {
      executor: 'ramping-vus',
      stages: [
        {duration: '20s', target: 10}, // Ramp-up to 10 users over 20 seconds
        {duration: '40s', target: 10},  // Stay at 10 users for 40 seconds
        {duration: '20s', target: 50}, // Ramp-up to 50 users over 20 seconds
        {duration: '40s', target: 50},  // Stay at 50 users for 40 seconds
        {duration: '20s', target: 100}, // Ramp-up to 100 users over 20 seconds
        {duration: '40s', target: 100}, // Stay at 100 users for 40 seconds
      ],
    },
  },
};

const BASE_URL = 'http://localhost:1993/api';

// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
  group('/v1/orders/{order_id}', () => {
    let orderId = '10c41c08-103b-481f-bfe0-241de68aa29f'; // specify value as there is no example value for this parameter in OpenAPI spec

    // Request No. 1:
    {
      let url = BASE_URL + `/v1/orders/${orderId}`;
      let request = http.get(url);

      check(request, {
        'OK': (r) => r.status === 200,
      });
    }
  });

  group('/v1/orders/{order_id}/status', () => {
    let orderId = '10c41c08-103b-481f-bfe0-241de68aa29f'; // specify value as there is no example value for this parameter in OpenAPI spec

    // Request No. 1:
    {
      let url = BASE_URL + `/v1/orders/${orderId}/status`;
      let body = {'status': 'confirmed'};
      let params = {
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
      };
      let request = http.patch(url, JSON.stringify(body), params);

      check(request, {
        'OK': (r) => r.status === 200,
      });
    }
  });

  group('/healthz', () => {

    // Request No. 1:
    {
      let url = BASE_URL + `/healthz`;
      let request = http.get(url);

      check(request, {
        'OK': (r) => r.status === 200,
      });
    }
  });

  group('/v1/orders',
      () => {
        let size = '10'; // specify value as there is no example value for this parameter in OpenAPI spec
        let page = '1'; // specify value as there is no example value for this parameter in OpenAPI spec
        let restaurantId = ''; // specify value as there is no example value for this parameter in OpenAPI spec
        let userId = ''; // specify value as there is no example value for this parameter in OpenAPI spec
        let status = ''; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1:
        {
          let url = BASE_URL +
              `/v1/orders?page=${page}&restaurant_id=${restaurantId}&size=${size}&status=${status}&user_id=${userId}`;
          let request = http.get(url);

          check(request, {
            'List orders ok': (r) => r.status === 200,
          });

          sleep(SLEEP_DURATION);
        }

        // Request No. 2:
        {
          let url = BASE_URL + `/v1/orders`;
          let body = {
            'items': [
              {
                'menu_item_id': 'ea6e7260-24c1-4e2b-ba60-66e4e22a8466',
                'quantity': 5,
              },
              {
                'menu_item_id': 'c2664879-8aa9-40a1-9d8f-c3f84ab438db',
                'quantity': 3,
              },
            ],
            'restaurant_id': '471e0637-016a-4727-aefe-1a791ed68041',
            'user_id': 'adcf23bc-cd32-4176-8d46-68f15ebdfa98',
          };
          let params = {
            headers: {
              'Content-Type': 'application/json',
              'Accept': 'application/json',
            },
          };
          let request = http.post(url, JSON.stringify(body), params);

          check(request, {
            'Create order ok': (r) => r.status === 200,
          });
        }
      });
}
