/*
 * Godine User Restful API
 * Godine User Restful API document.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: blackhorseya@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * Generator version: 7.7.0-SNAPSHOT
 */

import http from 'k6/http';
import {check, group, sleep} from 'k6';
import errorHandler from './errorHandler.js';

const BASE_URL = 'http://localhost:1994/api';
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
  group('/v1/users/{id}', () => {
    let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

    // Request No. 1:
    {
      let url = BASE_URL + `/v1/users/${id}`;
      let request = http.get(url);

      errorHandler.logError(!check(request, {
        'OK': (r) => r.status === 200,
      }), request);

      sleep(SLEEP_DURATION);
    }

    // Request No. 2:
    {
      let url = BASE_URL + `/v1/users/${id}`;
      let request = http.del(url);

      errorHandler.logError(!check(request, {
        'No Content': (r) => r.status === 204,
      }), request);
    }
  });

  group('/v1/users/{id}/status', () => {
    let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

    // Request No. 1:
    {
      let url = BASE_URL + `/v1/users/${id}/status`;
      // TODO: edit the parameters of the request body.
      let body = {'isActive': 'boolean'};
      let params = {
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
      };
      let request = http.patch(url, JSON.stringify(body), params);

      errorHandler.logError(!check(request, {
        'OK': (r) => r.status === 200,
      }), request);
    }
  });

  group('/v1/users', () => {
    let size = 'TODO_EDIT_THE_SIZE'; // specify value as there is no example value for this parameter in OpenAPI spec
    let page = 'TODO_EDIT_THE_PAGE'; // specify value as there is no example value for this parameter in OpenAPI spec

    // Request No. 1:
    {
      let url = BASE_URL + `/v1/users?page=${page}&size=${size}`;
      let request = http.get(url);

      errorHandler.logError(!check(request, {
        'OK': (r) => r.status === 200,
      }), request);

      sleep(SLEEP_DURATION);
    }

    // Request No. 2:
    {
      let url = BASE_URL + `/v1/users`;
      // TODO: edit the parameters of the request body.
      let body = {
        'address': {
          'city': 'string',
          'state': 'string',
          'street': 'string',
          'zipCode': 'string',
        }, 'email': 'string', 'name': 'string', 'password': 'string',
      };
      let params = {
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
      };
      let request = http.post(url, JSON.stringify(body), params);

      errorHandler.logError(!check(request, {
        'OK': (r) => r.status === 200,
      }), request);
    }
  });

  group('/healthz', () => {

    // Request No. 1:
    {
      let url = BASE_URL + `/healthz`;
      let request = http.get(url);

      errorHandler.logError(!check(request, {
        'OK': (r) => r.status === 200,
      }), request);
    }
  });
}
