basePath: /api
definitions:
  github_com_blackhorseya_godine_entity_order_model.Order:
    properties:
      created_at:
        description: CreatedAt is the timestamp when the order was created.
        type: string
      id:
        description: ID is the unique identifier of the order.
        type: string
      items:
        description: Items are the list of items in the order.
        items:
          $ref: '#/definitions/github_com_blackhorseya_godine_entity_order_model.OrderItem'
        type: array
      restaurant_id:
        description: RestaurantID is the identifier of the restaurant where the order
          was placed.
        type: string
      status:
        description: Status is the current status of the order (e.g., pending, confirmed,
          delivered).
        type: string
      total_amount:
        description: TotalAmount is the total amount of the order.
        type: number
      updated_at:
        description: UpdatedAt is the timestamp when the order was last updated.
        type: string
      user_id:
        description: UserID is the identifier of the user who placed the order.
        type: string
    type: object
  github_com_blackhorseya_godine_entity_order_model.OrderItem:
    properties:
      menu_item_id:
        description: MenuItemID is the identifier of the menu item.
        type: string
      price:
        description: Price is the price of a single unit of the menu item.
        type: number
      quantity:
        description: Quantity is the quantity of the menu item ordered.
        type: integer
    type: object
  orders.PostPayload:
    properties:
      restaurant_id:
        example: a1dbb32b-05f0-4354-8253-60f4c6deae12
        type: string
      user_id:
        example: adcf23bc-cd32-4176-8d46-68f15ebdfa98
        type: string
    required:
    - restaurant_id
    - user_id
    type: object
  responsex.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact:
    email: blackhorseya@gmail.com
    name: Sean Zheng
    url: https://blog.seancheng.space
  description: Godine Order Restful API document.
  license:
    name: GPL-3.0
    url: https://spdx.org/licenses/GPL-3.0-only.html
  title: Godine Order Restful API
  version: 0.1.0
paths:
  /healthz:
    get:
      consumes:
      - application/json
      description: Check the health of the service.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      summary: Check the health of the service.
      tags:
      - health
  /v1/orders:
    post:
      consumes:
      - application/json
      description: Create a new order
      parameters:
      - description: order payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/orders.PostPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responsex.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_blackhorseya_godine_entity_order_model.Order'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      security:
      - Bearer: []
      summary: Create a new order
      tags:
      - orders
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
