basePath: /api
definitions:
  github_com_blackhorseya_godine_entity_domain_order_model.Order:
    properties:
      created_at:
        description: CreatedAt is the timestamp when the order was created.
        type: string
      delivery_id:
        description: DeliveryID is the identifier of the delivery associated with
          the order.
        type: string
      id:
        description: ID is the unique identifier of the order.
        type: string
      items:
        description: Items are the list of items in the order.
        items:
          $ref: '#/definitions/github_com_blackhorseya_godine_entity_domain_order_model.OrderItem'
        type: array
      restaurant_id:
        description: RestaurantID is the identifier of the restaurant where the order
          was placed.
        type: string
      status:
        description: Status is the current status of the order (e.g., pending, confirmed,
          delivered).
      total_amount:
        description: TotalAmount is the total amount of the order.
        type: number
      updated_at:
        description: UpdatedAt is the timestamp when the order was last updated.
        type: string
      user_id:
        description: UserID is the identifier of the user who placed the order.
        type: string
    type: object
  github_com_blackhorseya_godine_entity_domain_order_model.OrderItem:
    properties:
      menu_item_id:
        description: MenuItemID is the identifier of the menu item.
        example: 174e9519-4c47-42f2-bb1c-b0eaa8f76d05
        type: string
      price:
        description: Price is the price of a single unit of the menu item.
        example: 10
        type: number
      quantity:
        description: Quantity is the quantity of the menu item ordered.
        example: 2
        type: integer
    type: object
  orders.PatchWithStatusPayload:
    properties:
      status:
        example: confirmed
        type: string
    required:
    - status
    type: object
  orders.PostPayload:
    properties:
      items:
        items:
          $ref: '#/definitions/github_com_blackhorseya_godine_entity_domain_order_model.OrderItem'
        type: array
      restaurant_id:
        type: string
      user_id:
        example: adcf23bc-cd32-4176-8d46-68f15ebdfa98
        type: string
    required:
    - items
    - restaurant_id
    - user_id
    type: object
  responsex.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact:
    email: blackhorseya@gmail.com
    name: Sean Zheng
    url: https://blog.seancheng.space
  description: Godine Order Restful API document.
  license:
    name: GPL-3.0
    url: https://spdx.org/licenses/GPL-3.0-only.html
  title: Godine Order Restful API
  version: 0.1.0
paths:
  /healthz:
    get:
      consumes:
      - application/json
      description: Check the health of the service.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      summary: Check the health of the service.
      tags:
      - health
  /v1/orders:
    get:
      consumes:
      - application/json
      description: Get order list
      parameters:
      - default: 1
        description: Page is the page number.
        in: query
        minimum: 1
        name: page
        type: integer
      - description: RestaurantID is the ID of the restaurant that received the order.
        in: query
        name: restaurant_id
        type: string
      - default: 10
        description: Size is the number of items per page.
        in: query
        maximum: 100
        minimum: 1
        name: size
        type: integer
      - description: Status is the status of the order.
        enum:
        - pending
        - confirmed
        - preparing
        - delivering
        - delivered
        - canceled
        in: query
        name: status
        type: string
      - description: UserID is the ID of the user who placed the order.
        in: query
        name: user_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Total-Count:
              description: Total number of items
              type: number
          schema:
            allOf:
            - $ref: '#/definitions/responsex.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_blackhorseya_godine_entity_domain_order_model.Order'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      security:
      - Bearer: []
      summary: Get order list
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: Create a new order
      parameters:
      - description: order payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/orders.PostPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responsex.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_blackhorseya_godine_entity_domain_order_model.Order'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      security:
      - Bearer: []
      summary: Create a new order
      tags:
      - orders
  /v1/orders/{order_id}:
    get:
      consumes:
      - application/json
      description: Get order by id
      parameters:
      - description: order id
        in: path
        name: order_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responsex.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_blackhorseya_godine_entity_domain_order_model.Order'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      security:
      - Bearer: []
      summary: Get order by id
      tags:
      - orders
  /v1/orders/{order_id}/status:
    patch:
      consumes:
      - application/json
      description: Update order status
      parameters:
      - description: order id
        in: path
        name: order_id
        required: true
        type: string
      - description: order status payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/orders.PatchWithStatusPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responsex.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_blackhorseya_godine_entity_domain_order_model.Order'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsex.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      security:
      - Bearer: []
      summary: Update order status
      tags:
      - orders
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
