// Code generated by MockGen. DO NOT EDIT.
// Source: notification.go
//
// Generated by this command:
//
//	mockgen -destination=./mock_notification.go -package=repo -source=notification.go
//

// Package repo is a generated GoMock package.
package repo

import (
	context "context"
	reflect "reflect"

	model "github.com/blackhorseya/godine/entity/domain/notification/model"
	utils "github.com/blackhorseya/godine/pkg/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockINotificationRepo is a mock of INotificationRepo interface.
type MockINotificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockINotificationRepoMockRecorder
}

// MockINotificationRepoMockRecorder is the mock recorder for MockINotificationRepo.
type MockINotificationRepoMockRecorder struct {
	mock *MockINotificationRepo
}

// NewMockINotificationRepo creates a new mock instance.
func NewMockINotificationRepo(ctrl *gomock.Controller) *MockINotificationRepo {
	mock := &MockINotificationRepo{ctrl: ctrl}
	mock.recorder = &MockINotificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINotificationRepo) EXPECT() *MockINotificationRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockINotificationRepo) Create(c context.Context, item *model.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockINotificationRepoMockRecorder) Create(c, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockINotificationRepo)(nil).Create), c, item)
}

// Delete mocks base method.
func (m *MockINotificationRepo) Delete(c context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockINotificationRepoMockRecorder) Delete(c, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockINotificationRepo)(nil).Delete), c, id)
}

// GetByID mocks base method.
func (m *MockINotificationRepo) GetByID(c context.Context, id string) (*model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", c, id)
	ret0, _ := ret[0].(*model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockINotificationRepoMockRecorder) GetByID(c, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockINotificationRepo)(nil).GetByID), c, id)
}

// List mocks base method.
func (m *MockINotificationRepo) List(c context.Context, cond utils.ListCondition) ([]*model.Notification, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", c, cond)
	ret0, _ := ret[0].([]*model.Notification)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockINotificationRepoMockRecorder) List(c, cond any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockINotificationRepo)(nil).List), c, cond)
}

// Update mocks base method.
func (m *MockINotificationRepo) Update(c context.Context, item *model.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockINotificationRepoMockRecorder) Update(c, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockINotificationRepo)(nil).Update), c, item)
}
