basePath: /api
definitions:
  deliveries.PatchWithStatusPayload:
    properties:
      status:
        example: delivered
        type: string
    required:
    - status
    type: object
  github_com_blackhorseya_godine_entity_domain_logistics_model.Delivery:
    properties:
      created_at:
        description: CreatedAt is the timestamp when the delivery was created.
        type: string
      delivery_time:
        description: DeliveryTime is the timestamp when the delivery was completed.
        type: string
      driver_id:
        description: DriverID is the identifier of the driver assigned to the delivery.
        type: string
      id:
        description: ID is the unique identifier of the delivery.
        type: string
      order_id:
        description: OrderID is the identifier of the order associated with the delivery.
        type: string
      pickup_time:
        description: PickupTime is the timestamp when the delivery was picked up.
        type: string
      status:
        description: Status is the current status of the delivery (e.g., pending,
          in transit, delivered).
      updated_at:
        description: UpdatedAt is the timestamp when the delivery was last updated.
        type: string
      user_id:
        description: UserID is the identifier of the user who placed the order.
        type: string
    type: object
  responsex.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact:
    email: blackhorseya@gmail.com
    name: Sean Zheng
    url: https://blog.seancheng.space
  description: Godine Logistics Restful API document.
  license:
    name: GPL-3.0
    url: https://spdx.org/licenses/GPL-3.0-only.html
  title: Godine Logistics Restful API
  version: 0.1.0
paths:
  /healthz:
    get:
      consumes:
      - application/json
      description: Check the health of the service.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      summary: Check the health of the service.
      tags:
      - health
  /v1/deliveries:
    get:
      consumes:
      - application/json
      description: Get the list of deliveries
      parameters:
      - description: driver id
        example: adcf23bc-cd32-4176-8d46-68f15ebdfa98
        in: query
        name: driver_id
        type: string
      - default: 1
        description: Page specifies the page number for pagination.
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 10
        description: Size specifies the number of items per page.
        in: query
        maximum: 100
        minimum: 1
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Total-Count:
              description: total count
              type: number
          schema:
            allOf:
            - $ref: '#/definitions/responsex.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_blackhorseya_godine_entity_domain_logistics_model.Delivery'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      security:
      - Bearer: []
      summary: Get the list of deliveries
      tags:
      - deliveries
    post:
      consumes:
      - application/json
      description: Create a new delivery
      parameters:
      - description: delivery request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_blackhorseya_godine_entity_domain_logistics_model.Delivery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responsex.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_blackhorseya_godine_entity_domain_logistics_model.Delivery'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      security:
      - Bearer: []
      summary: Create a new delivery
      tags:
      - deliveries
  /v1/deliveries/{id}:
    get:
      consumes:
      - application/json
      description: Get the delivery by id
      parameters:
      - description: delivery id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responsex.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_blackhorseya_godine_entity_domain_logistics_model.Delivery'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsex.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      security:
      - Bearer: []
      summary: Get the delivery by id
      tags:
      - deliveries
  /v1/deliveries/{id}/status:
    patch:
      consumes:
      - application/json
      description: Update the delivery status
      parameters:
      - description: delivery id
        in: path
        name: id
        required: true
        type: string
      - description: delivery status request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/deliveries.PatchWithStatusPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responsex.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_blackhorseya_godine_entity_domain_logistics_model.Delivery'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsex.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      security:
      - Bearer: []
      summary: Update the delivery status
      tags:
      - deliveries
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
