// Code generated by MockGen. DO NOT EDIT.
// Source: delivery.go
//
// Generated by this command:
//
//	mockgen -destination=./mock_delivery.go -package=repo -source=delivery.go
//

// Package repo is a generated GoMock package.
package repo

import (
	context "context"
	reflect "reflect"

	model "github.com/blackhorseya/godine/entity/domain/logistics/model"
	utils "github.com/blackhorseya/godine/pkg/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockIDeliveryRepo is a mock of IDeliveryRepo interface.
type MockIDeliveryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIDeliveryRepoMockRecorder
}

// MockIDeliveryRepoMockRecorder is the mock recorder for MockIDeliveryRepo.
type MockIDeliveryRepoMockRecorder struct {
	mock *MockIDeliveryRepo
}

// NewMockIDeliveryRepo creates a new mock instance.
func NewMockIDeliveryRepo(ctrl *gomock.Controller) *MockIDeliveryRepo {
	mock := &MockIDeliveryRepo{ctrl: ctrl}
	mock.recorder = &MockIDeliveryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDeliveryRepo) EXPECT() *MockIDeliveryRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIDeliveryRepo) Create(c context.Context, item *model.Delivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIDeliveryRepoMockRecorder) Create(c, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIDeliveryRepo)(nil).Create), c, item)
}

// Delete mocks base method.
func (m *MockIDeliveryRepo) Delete(c context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIDeliveryRepoMockRecorder) Delete(c, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIDeliveryRepo)(nil).Delete), c, id)
}

// GetByID mocks base method.
func (m *MockIDeliveryRepo) GetByID(c context.Context, id string) (*model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", c, id)
	ret0, _ := ret[0].(*model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIDeliveryRepoMockRecorder) GetByID(c, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIDeliveryRepo)(nil).GetByID), c, id)
}

// List mocks base method.
func (m *MockIDeliveryRepo) List(c context.Context, cond utils.Pagination) ([]*model.Delivery, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", c, cond)
	ret0, _ := ret[0].([]*model.Delivery)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIDeliveryRepoMockRecorder) List(c, cond any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIDeliveryRepo)(nil).List), c, cond)
}

// Update mocks base method.
func (m *MockIDeliveryRepo) Update(c context.Context, item *model.Delivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIDeliveryRepoMockRecorder) Update(c, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIDeliveryRepo)(nil).Update), c, item)
}
