restaurantRestful:
  name: godine-restaurant-restful

  log:
    level: debug
    format: console

  http:
    url: http://restaurant_restful:1992
    port: 1992
    mode: debug

  storage:
    mongodb:
      dsn: mongodb://admin:changeme@mongodb/?retryWrites=true&w=majority

  otel:
    target: otel-collector:4317

orderRestful:
  name: godine-order-restful

  log:
    level: debug
    format: console

  http:
    url: http://order_restful:1993
    port: 1993
    mode: debug

  storage:
    mongodb:
      dsn: mongodb://admin:changeme@mongodb/?retryWrites=true&w=majority

  otel:
    target: otel-collector:4317

userRestful:
  name: godine-user-restful

  log:
    level: debug
    format: console

  http:
    url: http://user_restful:1994
    port: 1994
    mode: debug

  storage:
    mongodb:
      dsn: mongodb://admin:changeme@mongodb/?retryWrites=true&w=majority

  otel:
    target: otel-collector:4317

logisticsRestful:
  name: godine-logistics-restful

  log:
    level: debug
    format: console

  http:
    url: http://logistics_restful:1995
    port: 1995
    mode: debug

  storage:
    mongodb:
      dsn: mongodb://admin:changeme@mongodb/?retryWrites=true&w=majority

  kafka:
    brokers:
      - kafka:9092
    username:
    password:

  otel:
    target: otel-collector:4317

notifyRestful:
  name: godine-notify-restful

  log:
    level: debug
    format: console

  http:
    url: http://notify_restful:1996
    port: 1996
    mode: debug

  storage:
    mongodb:
      dsn: mongodb://admin:changeme@mongodb/?retryWrites=true&w=majority

  otel:
    target: otel-collector:4317
