// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package biz

import (
	"github.com/blackhorseya/godine/app/domain/restaurant/repo/restaurant"
	"github.com/blackhorseya/godine/entity/domain/restaurant/biz"
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func NewIntegration(rw *mongo.Client, rdb *redis.Client) (biz.RestaurantServiceServer, error) {
	iRestaurantRepo := restaurant.NewMongodb(rw, rdb)
	restaurantServiceServer := NewRestaurantService(iRestaurantRepo)
	return restaurantServiceServer, nil
}

// wire.go:

// ProviderRestaurantBizSet is a provider set for restaurant biz.
var ProviderRestaurantBizSet = wire.NewSet(
	NewRestaurantService,
	NewMenuService, restaurant.NewMongodb,
)
