// Code generated by MockGen. DO NOT EDIT.
// Source: restaurant.go
//
// Generated by this command:
//
//	mockgen -destination=./mock_restaurant.go -package=repo -source=restaurant.go
//

// Package repo is a generated GoMock package.
package repo

import (
	context "context"
	reflect "reflect"

	model "github.com/blackhorseya/godine/entity/domain/restaurant/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIRestaurantRepo is a mock of IRestaurantRepo interface.
type MockIRestaurantRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIRestaurantRepoMockRecorder
}

// MockIRestaurantRepoMockRecorder is the mock recorder for MockIRestaurantRepo.
type MockIRestaurantRepoMockRecorder struct {
	mock *MockIRestaurantRepo
}

// NewMockIRestaurantRepo creates a new mock instance.
func NewMockIRestaurantRepo(ctrl *gomock.Controller) *MockIRestaurantRepo {
	mock := &MockIRestaurantRepo{ctrl: ctrl}
	mock.recorder = &MockIRestaurantRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRestaurantRepo) EXPECT() *MockIRestaurantRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIRestaurantRepo) Create(c context.Context, data *model.Restaurant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", c, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIRestaurantRepoMockRecorder) Create(c, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIRestaurantRepo)(nil).Create), c, data)
}

// Delete mocks base method.
func (m *MockIRestaurantRepo) Delete(c context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIRestaurantRepoMockRecorder) Delete(c, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIRestaurantRepo)(nil).Delete), c, id)
}

// GetByID mocks base method.
func (m *MockIRestaurantRepo) GetByID(c context.Context, id string) (*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", c, id)
	ret0, _ := ret[0].(*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIRestaurantRepoMockRecorder) GetByID(c, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIRestaurantRepo)(nil).GetByID), c, id)
}

// List mocks base method.
func (m *MockIRestaurantRepo) List(c context.Context, condition ListCondition) ([]*model.Restaurant, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", c, condition)
	ret0, _ := ret[0].([]*model.Restaurant)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIRestaurantRepoMockRecorder) List(c, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIRestaurantRepo)(nil).List), c, condition)
}

// Update mocks base method.
func (m *MockIRestaurantRepo) Update(c context.Context, data *model.Restaurant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", c, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIRestaurantRepoMockRecorder) Update(c, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIRestaurantRepo)(nil).Update), c, data)
}
