// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpc

import (
	"fmt"
	"github.com/blackhorseya/godine/adapter/platform/wirex"
	biz5 "github.com/blackhorseya/godine/app/domain/logistics/biz"
	"github.com/blackhorseya/godine/app/domain/logistics/repo/delivery"
	biz4 "github.com/blackhorseya/godine/app/domain/notification/biz"
	"github.com/blackhorseya/godine/app/domain/notification/repo/notification"
	biz6 "github.com/blackhorseya/godine/app/domain/order/biz"
	"github.com/blackhorseya/godine/app/domain/order/repo/order"
	biz3 "github.com/blackhorseya/godine/app/domain/payment/biz"
	"github.com/blackhorseya/godine/app/domain/payment/repo/payment"
	biz2 "github.com/blackhorseya/godine/app/domain/restaurant/biz"
	"github.com/blackhorseya/godine/app/domain/restaurant/repo/restaurant"
	"github.com/blackhorseya/godine/app/domain/user/biz"
	"github.com/blackhorseya/godine/app/infra/authx"
	"github.com/blackhorseya/godine/app/infra/configx"
	"github.com/blackhorseya/godine/app/infra/otelx"
	"github.com/blackhorseya/godine/app/infra/snowflakex"
	"github.com/blackhorseya/godine/app/infra/storage/mongodbx"
	"github.com/blackhorseya/godine/app/infra/storage/postgresqlx"
	"github.com/blackhorseya/godine/app/infra/storage/redix"
	"github.com/blackhorseya/godine/app/infra/transports/grpcx"
	"github.com/blackhorseya/godine/app/infra/transports/httpx"
	biz12 "github.com/blackhorseya/godine/entity/domain/logistics/biz"
	biz10 "github.com/blackhorseya/godine/entity/domain/notification/biz"
	biz11 "github.com/blackhorseya/godine/entity/domain/order/biz"
	biz9 "github.com/blackhorseya/godine/entity/domain/payment/biz"
	biz8 "github.com/blackhorseya/godine/entity/domain/restaurant/biz"
	biz7 "github.com/blackhorseya/godine/entity/domain/user/biz"
	"github.com/blackhorseya/godine/pkg/adapterx"
	"github.com/blackhorseya/godine/pkg/contextx"
	"github.com/spf13/viper"
	"google.golang.org/grpc"
	"google.golang.org/grpc/health"
	"google.golang.org/grpc/health/grpc_health_v1"
	"google.golang.org/grpc/reflection"
)

// Injectors from wire.go:

func New(v *viper.Viper) (adapterx.Restful, error) {
	configuration, err := configx.NewConfiguration(v)
	if err != nil {
		return nil, err
	}
	application, err := initApplication(configuration)
	if err != nil {
		return nil, err
	}
	authxAuthx, err := authx.New(application)
	if err != nil {
		return nil, err
	}
	injector := &wirex.Injector{
		C:     configuration,
		A:     application,
		Authx: authxAuthx,
	}
	accountServiceServer := biz.NewAccountService()
	client, err := mongodbx.NewClient(application)
	if err != nil {
		return nil, err
	}
	redisClient, err := redix.NewClient(application)
	if err != nil {
		return nil, err
	}
	iRestaurantRepo := restaurant.NewMongodb(client, redisClient)
	restaurantServiceServer := biz2.NewRestaurantService(iRestaurantRepo)
	menuServiceServer := biz2.NewMenuService(iRestaurantRepo)
	iPaymentRepo := payment.NewMongodb(client)
	paymentServiceServer := biz3.NewPaymentService(iPaymentRepo)
	iNotificationRepo := notification.NewMongodb(client)
	notificationServiceServer := biz4.NewNotificationService(iNotificationRepo)
	db, err := postgresqlx.NewClient(application)
	if err != nil {
		return nil, err
	}
	node, err := snowflakex.NewNode()
	if err != nil {
		return nil, err
	}
	iOrderRepo, err := order.NewGORM(db, node)
	if err != nil {
		return nil, err
	}
	grpcxClient, err := grpcx.NewClient(configuration)
	if err != nil {
		return nil, err
	}
	restaurantServiceClient, err := biz2.NewRestaurantServiceClient(grpcxClient)
	if err != nil {
		return nil, err
	}
	menuServiceClient, err := biz2.NewMenuServiceClient(grpcxClient)
	if err != nil {
		return nil, err
	}
	accountServiceClient, err := biz.NewAccountServiceClient(grpcxClient)
	if err != nil {
		return nil, err
	}
	notificationServiceClient, err := biz4.NewNotificationServiceClient(grpcxClient)
	if err != nil {
		return nil, err
	}
	paymentServiceClient, err := biz3.NewPaymentServiceClient(grpcxClient)
	if err != nil {
		return nil, err
	}
	logisticsServiceClient, err := biz5.NewLogisticsServiceClient(grpcxClient)
	if err != nil {
		return nil, err
	}
	orderServiceServer := biz6.NewOrderService(iOrderRepo, restaurantServiceClient, menuServiceClient, accountServiceClient, notificationServiceClient, paymentServiceClient, logisticsServiceClient)
	iDeliveryRepo := delivery.NewMongodb(client)
	logisticsServiceServer := biz5.NewLogisticsService(iDeliveryRepo, notificationServiceClient)
	initServers := NewInitServersFn(accountServiceServer, restaurantServiceServer, menuServiceServer, paymentServiceServer, notificationServiceServer, orderServiceServer, logisticsServiceServer)
	server, err := grpcx.NewServer(application, initServers, authxAuthx)
	if err != nil {
		return nil, err
	}
	httpxServer, err := httpx.NewServer(application)
	if err != nil {
		return nil, err
	}
	restful := NewServer(injector, server, httpxServer)
	return restful, nil
}

// wire.go:

const serverName = "platform"

// NewInitServersFn creates and returns a new InitServers function.
func NewInitServersFn(
	accountServer biz7.AccountServiceServer,
	restaurantServer biz8.RestaurantServiceServer,
	menuServer biz8.MenuServiceServer,
	paymentServer biz9.PaymentServiceServer,
	notifyServer biz10.NotificationServiceServer,
	orderServer biz11.OrderServiceServer,
	logisticsServer biz12.LogisticsServiceServer,
) grpcx.InitServers {
	return func(s *grpc.Server) {
		healthServer := health.NewServer()
		grpc_health_v1.RegisterHealthServer(s, healthServer)
		healthServer.SetServingStatus(serverName, grpc_health_v1.HealthCheckResponse_SERVING)
		biz7.RegisterAccountServiceServer(s, accountServer)
		biz8.RegisterRestaurantServiceServer(s, restaurantServer)
		biz8.RegisterMenuServiceServer(s, menuServer)
		biz9.RegisterPaymentServiceServer(s, paymentServer)
		biz10.RegisterNotificationServiceServer(s, notifyServer)
		biz11.RegisterOrderServiceServer(s, orderServer)
		biz12.RegisterLogisticsServiceServer(s, logisticsServer)
		reflection.Register(s)
	}
}

func initApplication(config *configx.Configuration) (*configx.Application, error) {
	app, err := config.GetService(serverName)
	if err != nil {
		return nil, fmt.Errorf("failed to get service %s: %w", serverName, err)
	}

	err = otelx.SetupOTelSDK(contextx.Background(), app)
	if err != nil {
		return nil, fmt.Errorf("failed to setup otel sdk: %w", err)
	}

	return app, nil
}
