basePath: /api
definitions:
  github_com_blackhorseya_godine_entity_notification_model.Notification:
    properties:
      created_at:
        description: CreatedAt is the timestamp when the notification was created.
        type: string
      id:
        description: ID is the unique identifier of the notification.
        type: string
      message:
        description: Message is the content of the notification.
        type: string
      order_id:
        description: OrderID is the identifier of the order associated with the notification.
        type: string
      status:
        description: Status is the current status of the notification (e.g., pending,
          sent).
        type: string
      type:
        description: Type represents the type of notification (e.g., order_status,
          delivery_status).
        type: string
      updated_at:
        description: UpdatedAt is the timestamp when the notification was last updated.
        type: string
      user_id:
        description: UserID is the identifier of the user to whom the notification
          is sent.
        type: string
    type: object
  notifications.PostPayload:
    type: object
  responsex.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact:
    email: blackhorseya@gmail.com
    name: Sean Zheng
    url: https://blog.seancheng.space
  description: Godine Notification Restful API document.
  license:
    name: GPL-3.0
    url: https://spdx.org/licenses/GPL-3.0-only.html
  title: Godine Notification Restful API
  version: 0.1.0
paths:
  /healthz:
    get:
      consumes:
      - application/json
      description: Check the health of the service.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      summary: Check the health of the service.
      tags:
      - health
  /v1/notifications:
    get:
      consumes:
      - application/json
      description: Retrieve a list of notifications.
      parameters:
      - default: 1
        description: Page specifies the page number for pagination.
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 10
        description: Size specifies the number of items per page.
        in: query
        maximum: 100
        minimum: 1
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Total-Count:
              description: Total number of items
              type: int
          schema:
            allOf:
            - $ref: '#/definitions/responsex.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_blackhorseya_godine_entity_notification_model.Notification'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      security:
      - Bearer: []
      summary: Retrieve a list of notifications
      tags:
      - notifications
    post:
      consumes:
      - application/json
      description: Create a new notification.
      parameters:
      - description: The request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/notifications.PostPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/responsex.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_blackhorseya_godine_entity_notification_model.Notification'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      security:
      - Bearer: []
      summary: Create a new notification
      tags:
      - notifications
  /v1/notifications/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a notification by ID.
      parameters:
      - description: The notification ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responsex.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_blackhorseya_godine_entity_notification_model.Notification'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsex.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responsex.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsex.Response'
      security:
      - Bearer: []
      summary: Retrieve a notification by ID
      tags:
      - notifications
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
